# Generated by Django 6.0.1 on 2026-01-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
