# Generated by Django 6.0.1 on 2026-01-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_registeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='registeruser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
